apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myappresources.my.api.group
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: my.api.group
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicaCount:
                  type: integer
                resources:
                  type: object
                  properties:
                    memoryLimit:
                      type: string
                    cpuRequest:
                      type: string
                image:
                  type: object
                  properties:
                    repository:
                      type: string
                    tag:
                      type: string
                ui:
                  type: object
                  properties:
                    color:
                      type: string
                    message:
                      type: string
                redis:
                  type: object
                  properties:
                    enabled:
                      type: boolean
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: myappresources
    # singular name to be used as an alias on the CLI and for display
    singular: myappresource
    kind: MyAppResource
    shortNames:
    - mar
